### ISSUE TITLE
[EPIC] Ledger App Q3/2021

### ISSUE THREAD

**Issue by r4mmer** [HathorNetwork/ledger-app-hathor#10]
moved to: https://github.com/HathorNetwork/hathor-ledger-app/issues/2

# Q3 Ledger App Hathor

# July 14 - July 16

## Tasks
- [x] #11
- [x] **Document development docs, environment and tooling required**

# July 19 - July 23

## Tasks
- [x] #12
- [PARTIAL] #13
- [PARTIAL] #14
- [PARTIAL] #15
- [PARTIAL] #16
- [FAIL] **Unit and Integration tests**

### Features
:hourglass_flowing_sand: ledger app works with `nano S` firmware v2.0.0
:hourglass_flowing_sand: ledger can hold HTR tokens

# July 26 - July 30

## Tasks
- [x] #13
- [x] #14
- [x] #15
- [x] #16
- [FAIL] **Unit and Integration tests**
- [x] **Implement new ledger communication lib and tests**
- [x] **Implement ledger on wallet desktop**
- [x] #19

### Features
:hourglass_flowing_sand: Wallet Desktop can manage ledger hathor app
:hourglass_flowing_sand: App compatible with nano S and nano X
