### ISSUE TITLE
[EPIC] Ledger App Hathor August/2021

### ISSUE THREAD

**Issue by r4mmer** [HathorNetwork/ledger-app-hathor#17]
# Ledger App Hathor August/2021

## Tasks
- [ ] Transport layer abstraction from app client (this would allow BLE and web connections)
- [ ] Implement Ledger App on mobile wallet
- [ ] Add ledger client to hathor-wallet-lib

### Features
:x: Compatibility with `nano X` and other Ledger HW
:x: Hathor wallet mobile with Ledger
